version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt
